### ISSUE TITLE
Marathon mod compatibility - Recycling machines have vanilla cost

### ISSUE THREAD

**Issue by ianjirka** [DRY411S/Recycling-Machines#13]
Marathon adjusts resource costs of all recipes; this is likely a conflict in ordering for data updates.  In any case, the cost of the recycling machine is not updated by Marathon and is therefore much cheaper than it should be (Recycling 1 should be 25x of each ingredient).

Not sure the best way to fix this, but FYI.

**Comment by DRY411S** [comment]
Thanks for the information.

I guess that's going to an issue for almost all mods that produce new entities (like the Recycling Machines in my mod), and where people also want to use those mods with Marathon Mod.

I'm fairly sure my Recycling recipes are produced after Marathon mod has changed 'vanilla', so the 'recycling recipes' are an exact reverse of the Marathon recipes, but I'll check.

As for the recipes for the Recyclling Machines themselves, I'm not really sure what I can do.

**Comment by ianjirka** [comment]
As far as I've noticed the non-machine recipes are working just fine; I haven't seen an issue there.
I worked around it for now by hard-coding the machine recipes; perhaps you can pull the values from the marathon mod directly, if the mod exists.  I've done that sort of thing before.

**Comment by ianjirka** [comment]
Or you could ask/create a pull request for Marathon to support these recyclers.  Marathon already has special cases for a number of mods.

**Comment by DRY411S** [comment]
I think I can change the Recycling Machine recipes easily enough, and change them if Marathon Mod is installed, so Recycling Machines are as'expensive' as Assembly Machines.

**Comment by DRY411S** [comment]
I now have code in test that increase the Recycling Machine recipes if the Marathon mod is installed. Will be released when I've worked out how to write the migration/upgrade script (if it's possible at all).

**Comment by ianjirka** [comment]
Ok cool - Thanks!.  If you want me to test it out let me know; I can do so tonight.
