### ISSUE TITLE
No locale for the recycling recipes

### ISSUE THREAD

**Issue by DRY411S** [DRY411S/Recycling-Machines#2]
If a recycling recipe produces more than one result, there is no locale setting for it.

This problem can be partially fixed for 'vanilla' recycling, when the mod can be sure of what things require recycling, but when the mod finds non-vanilla recipes for other mods, this mod won't have a locale setting available.

**Comment by Simcra** [comment]
Try removing the prefix from recipes and adding a suffix of -9999 or some arbitrary number, if I remember correctly, they will inherit their regular recipe locale.

**Comment by DRY411S** [comment]
> Try removing the prefix from recipes and adding a suffix of -9999 or some arbitrary number, if I remember correctly, they will inherit their regular recipe locale.

Can you reference something on the net that confirms this? I cannot find anything.

**Comment by Simcra** [comment]
In my mod Surfaces (https://github.com/Simcra/Surfaces) I have no recipe-name in my locale file and my recipes are all localised in-game, there is no documentation that confirms this. Further clarification: if you have a mod which adds recipes like "ladder", "ladder-1", "ladder-2", "ladder-3", each of incremented recipe names will copy the locale from the main recipe unless specifically stated. You would have to check data.raw for these incrementally and set the name of the reverse recipe to the next available number recipe. For example: if I have wood-plank, wood-plank-1, wood-plank-2, you'd add wood-plank-3, wood-plank-4 and wood-plank-5 as the reverse recipes and they would all gain the locale from wood-plank.

**Comment by DRY411S** [comment]
Thanks for the hint. I will take a look. It doesn't fix the overall problem though that Factorio assumes that an assembling machine produces only one output. The locale 'reverse recipe' name for the Recycling Machine is used for the inputs AND the outputs (unless there is only 1 output).

**Comment by DRY411S** [comment]
This link is much better advice. It's in test at the moment.

[](https://forums.factorio.com/viewtopic.php?f=97&t=26039&p=183229#p183183)

**Comment by DRY411S** [comment]
Vanilla locale added. Reclassifying as an enhancement to support other mods.

**Comment by DRY411S** [comment]
Locale for Bob's Mods also added

**Comment by DRY411S** [comment]
Locale for 5dim's mods added in v0.13.16

**Comment by DRY411S** [comment]
This is now fixed for Vanilla, Yuoki Industries, Bob's Mods and 5dim Mods. Every individual mod's locale issue will be raised as a separate issue.
