### ISSUE TITLE
Recycling icons in crafting menus are the wrong size

### ISSUE THREAD

**Issue by DRY411S** [DRY411S/Recycling-Machines#28]
Due to v0.15 using different size icons in the crafting tabs, this mod now needs new icons.

**Comment by zone1135** [comment]
I did some fiddling and I don't think the icon sizes changed. When replacing the icons used with vanilla ones their sizes still seemed off. I modified some of the icons as a temporary fix.
![logistics](https://cloud.githubusercontent.com/assets/10016064/26022571/2bb7bfc8-37ec-11e7-8cca-a61b836ad6c2.png)
![military](https://cloud.githubusercontent.com/assets/10016064/26022569/2bb5c614-37ec-11e7-880b-63242fce4acf.png)
![production](https://cloud.githubusercontent.com/assets/10016064/26022574/2bcc074e-37ec-11e7-9609-70f909e77d6d.png)
![recycling](https://cloud.githubusercontent.com/assets/10016064/26022570/2bb71348-37ec-11e7-9ab0-7598d081d66c.png)
![signals](https://cloud.githubusercontent.com/assets/10016064/26022572/2bb9caca-37ec-11e7-85a3-2192a1915399.png)
![fluids](https://cloud.githubusercontent.com/assets/10016064/26022573/2bba4450-37ec-11e7-878b-da032d9d2a12.png)
![intermediate-products](https://cloud.githubusercontent.com/assets/10016064/26022575/2be63d12-37ec-11e7-9292-b2b200f2e6bc.png)

**Comment by DRY411S** [comment]
@zone1135 thanks for investigating and discovering that the vanilla icons are still 64x64. Mine are too. This suggests that the game is doing some kind of resizing of mine, but not the games stock icons.

I've discovered a new item-group property called 'icon-size'. I need to handle this in my code, to force the game to use 64x64.

I have something in test that works. It will be in the next release.
