### ISSUE TITLE
Text in recycling machine is misleading

### ISSUE THREAD

**Issue by DRY411S** [DRY411S/Recycling-Machines#4]
The text in a recycling machine menu says "Choose recipe for assembly" (in English). I'd like to change that if I can.

**Comment by DRY411S** [comment]
This can be amended in the mod locale, but any amendments also apply to vanilla assembling machines. It's hard to come up with text that both:

1. makes sense in both machines
2. fits in the space available

Therefore I won't fix.

**Comment by shadoxxhd** [comment]
What about "Choose recipe"?

**Comment by DRY411S** [comment]
> What about "Choose recipe"?

Because in a recycling machine you're choosing an item to recycle, not the recipe for something to be made. :)

There may be a way to fix this, by dynamically changing the locale entry when a player clicks on an assembling machine, then reverting on it when they close the recycling machine. Removing the "won't fix"

**Comment by RionEV** [comment]
I feel like "Choose assembly recipe" sidesteps both issues (of global localization changes and of avoiding the scripted data swap) as in context it refers either to the recipe you wish to assemble when assembling, or the recipe that was assembled when recycling, but I'm not sure if this is what you are looking for...? I suppose I'm assuming that there's a sense in which the assembly or recycling machine is being programmed with a recipe to work forwards or backwards through. It's still quite close to shadoxxhd's suggestion, though, so it might not work for you...

Either that, or "Choose factory job", but that's probably a little less indicative in all cases.

**Comment by DRY411S** [comment]
I think that now that there are layered icons on tabs, adding a recycling logo to the tabs, and leaving the text unchanged may be the way to go on this.

**Comment by DRY411S** [comment]
Replaced by #80 as a future enhancement.
