### ISSUE TITLE
Recycling Machine can only recycle 3 things

### ISSUE THREAD

**Issue by AbeKline** [DRY411S/Recycling-Machines#47]
Recycling Machine 3 can only recycle cluster grenades, energy shield mk2, and piercing shotgun shells in 16.27

**Comment by DRY411S** [comment]
![image](https://user-images.githubusercontent.com/19732374/36959029-be506234-2037-11e8-828d-c0225b5fbf5b.png)

Cannot reproduce. This is likely to be caused by mod/mods you are using.

In Vanilla, Sandbox scenario with all research performed, all these combat items can be recycled.

**Comment by AbeKline** [comment]
What can I upload? Is it possible to post my save? Or a log? 
To clarify, the recycling machine can only do those three items, the other three tabs don't even load.

**Comment by DRY411S** [comment]
Please upload your mod-list.json from your mods folder so I can see the mods you are using. factorio-current.log would be useful. Can you upload the save file to the cloud somewhere like google docs or Microsoft OneDrive?

(You may need to change the .json  and .log file extensions to something like .txt before GitHub will let you attach them.)

**Comment by AbeKline** [comment]
Save file: https://drive.google.com/open?id=15Nq-hgamtKibDL__jGJf0_rNaufZSKEf
Mods JSON 
{
  "mods": [
    {
      "name": "base",
      "enabled": true
    },
    {
      "name": "air-filtering",
      "enabled": false
    },
    {
      "name": "ZRecycling",
      "enabled": true
    }
  ]
}

**Comment by DRY411S** [comment]
That is v0.16.2 of my mod, which has known issues. Please update to latest version (0.16.7) and tell mw what happens.

**Comment by AbeKline** [comment]
Updated to 16.6 and it worked!. Thanks, sorry!
