### ISSUE TITLE
Missing graphics files

### ISSUE THREAD

**Issue by Zaflis** [DRY411S/Recycling-Machines#53]
The \prototypes\recyclingpipes.lua describes many .png files which don't exist in the graphics folder. There are lines for N, E, S, W directions but only S ones are included. This fails to load with mods: bobassembly and omnimatter-compression (requires omnilib).

![recycle_error](https://user-images.githubusercontent.com/1862429/54091185-a46f9c00-4385-11e9-8e4c-5fe99d7695a3.png)

**Comment by DRY411S** [comment]
Thanks for the report. I'll fix in the next release.

**Comment by DRY411S** [comment]
True that the other mods are saying that my mod is referencing non-existent files. Strange then that the game does not pick this up when loading my mod.
