### ISSUE TITLE
Recycling Recipes for hidden items are produced

### ISSUE THREAD

**Issue by DRY411S** [DRY411S/Recycling-Machines#61]
There are items in the game that are hidden and not normally available. Examples are railguns and railgun darts, small plane, loaders and electric energy interface.

Even though these items are not in the game, the Recycling Machines offer them in their menus as recyclable.

**Comment by Anton-V-K** [comment]
Can this be merged into 0.16 branch, so it is also fixed for the stable version of Factorio (0.16.51)?

**Comment by DRY411S** [comment]
> Can this be merged into 0.16 branch, so it is also fixed for the stable version of Factorio (0.16.51)?

It's not a real 'merge' in GitHub terms because I didn't know GitHub when I started using it. I may retrofit this fix (and others) in the future weeks, but this one is a 'false positive' compared to some of the others.

**Comment by DRY411S** [comment]
@Anton-V-K check out v0.16.7

  Features:
    - Adds French localisation for 0.16 version https://github.com/DRY411S/Recycling-Machines/issues/67
  Bugfixes:
    - Fixes Machines will not always recycle some items https://github.com/DRY411S/Recycling-Machines/issues/49
    - Fixes Cannot recycle batteries https://github.com/DRY411S/Recycling-Machines/issues/50
    - Fixes Error constructing localised text https://github.com/DRY411S/Recycling-Machines/issues/52
    - Fixes Recycling Recipes for hidden items are produced https://github.com/DRY411S/Recycling-Machines/issues/61
    - Fixes No recycle recipe for Cliff Explosives https://github.com/DRY411S/Recycling-Machines/issues/62
    - Fixes Items with small stack sizes cannot always be recycled https://github.com/DRY411S/Recycling-Machines/issues/63
    - Fixes Early game what can be recycled is confusing https://github.com/DRY411S/Recycling-Machines/issues/64

**Comment by Anton-V-K** [comment]
@DRY411S , thanks for the new release. Unfortunately my Factorio 0.16.51 can't load it - see #68
