### ISSUE TITLE
No recycle recipe for Explosives

### ISSUE THREAD

**Issue by StlyAu** [DRY411S/Recycling-Machines#62]
As the title says, there is no recipe to recycle Explosives or Cliff Explosives. You have everything else that uses Explosives with their recycle recipes (Landmines, Cluster grenades, Arty shells, Cannon shells, Rockets).

**Comment by StlyAu** [comment]
There also isn't any recipes for any of the Concretes

**Comment by DRY411S** [comment]
Thanks for the report. The lack of Recycling Recipes for all the things you mention is deliberate.They are treated like all the smelted items, which also cannot be recycled back into ore.

I will though take a look at the cliff explosives.

The problem with Modular Armor is ineteresting, something to do with stack sizes. I'm investigating this.

**Comment by DRY411S** [comment]
@StlyAu I've broken this into 2 separate issues as they require different investigations. Your report about modular armor is now issue #63 https://github.com/DRY411S/Recycling-Machines/issues/63
