### ISSUE TITLE
Further Explosives inquiry

### ISSUE THREAD

**Issue by StlyAu** [DRY411S/Recycling-Machines#66]
I know you fixed the other items in my previous issue, but I still have an issue with Explosives themselves not having a recycle recipe.

You allow Poison/Slowdown Capsule to be recycled into Steel, GCs and COAL.
You allow Grenades be recycled into Iron Plate and COAL. 
You allow Batteries to be recycled into Iron, Copper and SULF ACID. 
You allow BCs to be recycled into GCs, RCs and SULF ACID. 
You allow Electric Engines to be recycled into Engine, GC and LUBE.
You allow all Express belts (or higher with various mods) to be recycled into lower tier, Gears and LUBE.

Explosives are COAL, Sulfur and water.... how is this any different than the others since you allow others with Lube or Acid be recycled? If all these others are allowed, then Explosives themselves should be. If you're going to disallow Plastics (due to Petroleum), Solid Fuels, Concrete and Explosives, then all those listed above should be disallowed for the same reasons. Double standards are being set here with your current decision.

**Comment by DRY411S** [comment]
In general, the mod does not allow the recycling of anything that requires a chemical plant, or refinery. The rationale is that the chemical reaction cannot be reversed. The only exception is batteries, where in my opinion, the game shouldn't really 'assemble' them in a chemical plant in the first place. So even though they are made in a chemical plant, the mod lets you recycle them in an assembling machine.

Similarly, the mod DOES allow recycling of things that are made in assembling machine and which require fluids, like you describe. I consider the fluids as unchanged and therefore recoverable. The lube is part of the engine. Disassemble the engine and the lube flows out for example. (Admittedly that doesn't stretch to the blue chips, but I let that one pass.)

The mod does not allow 'unsmelting' of plates back into ores, or bricks back into stone.

As for the capsules, they are 'other wordly', and I couldn't see any reason not to recycle them. 

Finally, the mod does not recycle anything that the game classifies as 'terrain' (landfill, concrete, decorative concrete). Again, in my head, concrete requires chemistry for the 'curing' of the cement.

When the cliff explosives were introduced to the game, they were classified as 'terrain' and therefore not recyclable. You reported this as an issue, and when I reflected on it, I thought it was a good shout that the 'barrel bombs' that are cliff explosives could be recycled, and I added the feature.

These are not double standards, they are my standards.  So thanks for the feedback, but I won't be recycling any more of the products of chemical plants.
