### ISSUE TITLE
Error while loading recipe prototype "dry411srev-factory-1" (recipe)

### ISSUE THREAD

**Issue by Anton-V-K** [DRY411S/Recycling-Machines#68]
When I try to launch Factorio 0.16.51, it fails to load recently released [v0.16.7](https://github.com/DRY411S/Recycling-Machines/releases/tag/v0.16.7).
The error:
`  2.832 Mods to disable:Failed to load mods: Error while loading recipe prototype "dry411srev-factory-1" (recipe): Value must be a string in property tree at ROOT.recipe.dry411srev-factory-1.localised_name[1]`
`Modifications: Recycling Machines`
The previous version [0.16.5](https://github.com/DRY411S/Recycling-Machines/releases/tag/v0.16.5) was running good ( except for #61 )

**Comment by DRY411S** [comment]
That's a mod clash. Any idea what mod uses a recipe to produce a factory?

**Comment by DRY411S** [comment]
Found it. There's a typo in my fix for https://github.com/DRY411S/Recycling-Machines/issues/52
