### ISSUE TITLE
Less than perfect recycling

### ISSUE THREAD

**Issue by jandk** [DRY411S/Recycling-Machines#71]
Really like this mod, although it would be nice to disassemble things "imperfectly".

A lot of games that allow this kind of stuff give you a penalty. So you can't just go back and forth.

My guess is about 50% would work fine, rounded down. For example turrets would get you back 5 copper plates, 5 gears and 10 iron. This makes it feel more "fair" in my opinion.

**Comment by DRY411S** [comment]
You might like to check out the mod startup settings :)
