### ISSUE TITLE
Bob's Mods support

### ISSUE THREAD

**Issue by embermctillhawk** [DRY411S/Recycling-Machines#72]
Yes, it's me again. Shouldn't be so much of a hassle this time though, this is just a few missing subgroups/crafts from assorted Bob's mods that ought be added to `modplugins.lua`, some for support, some to ignore. This will fix, among other things, being unable to recycle `Copper Wire` and `Electronic Circuit` with certain Bob's mods installed under the new code.

- craft: water-pump [ignore, similar to air-pump]
- craft: bob-greenhouse [ignore, shouldn't ungrow trees]
- craft: electronics
- craft: electronics-machine

Regarding `bobmodules`; putting aside the questionable ethics/physics of disassembling items then using productivity effects to create more of the input item than you put in, there's several missing entries for `bobmodules`. This will fix being unable to recycle modules, or the `Beacon`, because `bobmodules` changes the recipe type.

- item-group: bobmodules
- item-subgroup: module-intermediates
- item-subgroup: speed-module
- item-subgroup: effectivity-module
- item-subgroup: productivity-module
- item-subgroup: pollution-create-module
- item-subgroup: pollution-clean-module
- item-subgroup: raw-speed-module
- item-subgroup: green-module
- item-subgroup: raw-productivity-module
- item-subgroup: god-module
- item-subgroup: module-beacon

Now, a point about `bobmodules` which requires a judgement call. There are three other missing item-subgroup's, but it might make more sense to add them to ignore.

- item-subgroup: raw-speed-module-combine
- item-subgroup: green-module-combine
- item-subgroup: raw-productivity-module-combine

The materials required to manufacture the modules, then combine them, is greater than the materials to directly craft the combined type. Thus one can make a stable infinite loop under 1:1 recycling by disassembling the combined module via specifically the combination recipe, disassembling the resulting modules, then assembling the materials directly into the combined module, pocketing the difference.

This may be a balance issue inherent to the concept of being able to recycle in Factorio and thus a non-issue, and it becomes far less prominent or simply irrelevant if one uses a harder recycling ratio anyways, but it is something to be noted.

EDIT EDIT: Nevermind that last edit, I'm investigating that further.

**Comment by DRY411S** [comment]
What version are you using?  v0.18.4 seems to address all your comments (apart from the 'judgement' paragraphs).

**Comment by embermctillhawk** [comment]
Right, I'm sorry. I thought I was on the latest version already. I was attempting to help with support for Bob's Mods but you are right. The only useful information here now is the note about combining bob's modules; but you have read it so I think I'll go ahead and close this, sorry.
