### ISSUE TITLE
Add a switch for productivity modules

### ISSUE THREAD

**Issue by DRY411S** [DRY411S/Recycling-Machines#75]
Assemble something
Recycle it in a machine with Productivity Modules
Get more back than you originally started with

That shouldn't be allowed, but is.
Some people will complain if I remove it.
So implement it as a startup switch so its optional?

**Comment by zephraph** [comment]
😄 seems like removing that should be okay. That really is a bug.

**Comment by DRY411S** [comment]
Actually, it was a requested feature a while back, but perhaps it should be an option, with the default being off.

**Comment by DRY411S** [comment]
I was confusing a previous request to support Productivity Modules in a different mod of mine (now deprecated). Productivity modules do not work in Recycling MAchines, and that's the way it's going to stay.
