### ISSUE TITLE
mod not working in 0.18.34

### ISSUE THREAD

**Issue by Dziq84** [DRY411S/Recycling-Machines#88]
Hello. In the latest version, mod appears in the 'modifications' list - but it's marked with red color, and no other info is shown (so I don't have more info why it's not starting at all).  This mod is a very, very important part of my game, absolutely must-have,  so I hope someone will realize what is going on. Cheers and thanks in advance for a fix ;p

**Comment by DRY411S** [comment]
![image](https://user-images.githubusercontent.com/19732374/86818525-661fe500-c07e-11ea-93ef-9b8213157ff7.png)
 My v0.18.34 factorio with latest version of the mod (0.18.9) works fine. This is not a bug in the mod.

**Comment by Dziq84** [comment]
strange, earlier it worked with current mods I have,  only after a game update it's stopped working :/

**Comment by Dziq84** [comment]
I just recovered 0.18.08 version of this mod and its working without problems :)

**Comment by DRY411S** [comment]
The current version 0.18.9 should work without error. You should not need to go back to a previous version.

It is possible that another of your mods have said that their mod is incompatible with mine, causing my mod to show as 'red', because you have selected the other mod,  but I don't know any other mods that do this.

**Comment by Dziq84** [comment]
I will try to narrow which mod is incompatible and then remove it... Except that another mod is important too, so I will try to discover what exactly causes incompatibility

**Comment by DRY411S** [comment]
You just need to click on each active mod, and see whether any of them say they are incompatible with Recycling Machines. I am not aware of any that are. No mod authors have ever contacted me about incompatability.

**Comment by Dziq84** [comment]
hmmm with your mod update (0.18.10) it seems to work again :)
