### ISSUE TITLE
Mod crashes when recipe amounts appear before the name

### ISSUE THREAD

**Issue by Ludibria2** [DRY411S/Recycling-Machines#89]
Good day!
Your mod is great and phenomenal!
I faced a misfortune with...

Error downloading ZRecycling with Enchanted Industries & Chemicals by Enchant3d
https://mods.factorio.com/mod/EnchantedIndustries

it says "Error while loading recipe prototype "dry411srev-wood-fiber" (recipe): Difficulty normal: Key "name" not found in properly tree at ROOT.recipe.dry411srev-wood-fiber.ingredients[0]

Can you please help me out with that?
Will be greatful for any assistance!)

**Comment by DRY411S** [comment]
Enchanted Industries & Chemicals mod adds a recipe called "wood".

However, "wood" is a vanilla item built into the game that should have no recipe.

There's nothing I can do to deal with this. I have contacted the author of Enchanted Industries & Chemicals and suggest that he changes the name of the recipe.

**Comment by DRY411S** [comment]
Actually, this IS a bug. The mod author has created recipes that specify the amount produced first, and then the name of the product. This is extremely unusual, but is valid and my mod does not handle it.

Reference: https://wiki.factorio.com/Types/ItemProductPrototype

**Comment by DRY411S** [comment]
Fixed in v1.0.2

**Comment by Ludibria2** [comment]
Sir, my deepest gratitude! 
It works perfectly!
I didn't even expect it to be fixed so fast.
Thank you so much.
