### ISSUE TITLE
Can't recycle Cursed-PI

### ISSUE THREAD

**Issue by FKuerten** [DRY411S/Recycling-Machines#9]
With ZRecycling 0.13.11 and Cursed-PI 0.2.3 (Factorio 0.13.6):
I cannot select the burner inserted created by Cursed-PI. (Nor can I see any other.)
Adding Cursed-PI as an optional dependency does not help (nor should it, considering Cursed-PI does not use data-final-fixes).

This applies to both existing and new games.

**Comment by DRY411S** [comment]
This is a bug. The code to handle 'unknown' mods like this is not working correctly.

**Comment by DRY411S** [comment]
Fixed in v01.2.36
Fixed in v0.13.12

This issue was not specific to Cursed-PI. Any mod which produces recipe results like 

```
    results = {
      {
        amount = 1,
        name = "recipe-name",
        type = "item"
      }
    }

``` 
was not being 'recycled'

**Comment by FKuerten** [comment]
Fixed for new games.
NOT fixed for existing saves.

**Comment by DRY411S** [comment]
> Fixed for new games.
NOT fixed for existing saves.

I think you mean existing saves where the mod has been used, not ALL existing saves. I'm sorry, but I cannot fix for existing saves where previous versions of this mod were used, due to factorio modding limitations.

**Comment by DRY411S** [comment]
Reopening. I _may_ be able to fix for existing saves.

**Comment by DRY411S** [comment]
I was being dumb. v0.13.14 will have a fix for this.
