### ISSUE TITLE
angelsinfiniteores dependency is missing an operator

### ISSUE THREAD

**Issue by JanSharp** [DRY411S/Recycling-Machines#92]
https://github.com/DRY411S/Recycling-Machines/blob/master/info.json#L37
i thought i'd let you know that that dependency (`(?) angelsinfiniteores 0.9.1`) is missing an operator

**Comment by DRY411S** [comment]
Good spot thank you. Will fix in the next version.

In fact, there is nothing in that mod which is recyclable. It's listed in the info.json just so I have record of what mods have been tested with my mod.

**Comment by JanSharp** [comment]
no probelm. My program failed to parse it so i thought i'd let you know ;)

**Comment by DRY411S** [comment]
Fixed in v1.0.4
