### ISSUE TITLE
update for Factorio 1.1.2

### ISSUE THREAD

**Issue by Dziq84** [DRY411S/Recycling-Machines#93]
Hello, is there a chance to have this mod updated for 1.1 version of Factorio?

**Comment by DRY411S** [comment]
I will hopefully be able to this within the next 7  days. I always try to make sure that the mod works with the latests stable, and the latest experimental versions.

**Comment by Dziq84** [comment]
Glad to 'hear',  I can't play without this mod :)  It's essential part of my gameplay, especially my current save.  Thanks in advance, I'll wait :)

**Comment by DRY411S** [comment]
Temporarily, if you unzip the mod, and use a text editor to change these info.json lines, I believe it will work (untested).

From

```
	"factorio_version":"1.0",
	"dependencies": ["base >= 1.0.0",
```

To

```
	"factorio_version":"1.1",
	"dependencies": ["base >= 1.1.0",
```

**Comment by DRY411S** [comment]
Release v1.1.4 for factorio 1.1 now available here and on the mod portal.
